name: 'BotGuard Security Scan'
description: 'Run automated security scans on your AI agent. Tests for prompt injection, jailbreaks, data extraction, and more.'
author: 'BotGuardAI'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  api-key:
    description: 'BotGuard API key. Get one at https://botguard.dev'
    required: true
  endpoint:
    description: 'Agent API endpoint URL to scan'
    required: false
  description:
    description: 'Agent description'
    required: false
    default: 'AI agent'
  system-prompt:
    description: 'System prompt text or path to file'
    required: false
  fail-threshold:
    description: 'Minimum score (0-100) to pass. Action fails if score is below this.'
    required: false
    default: '0'
  categories:
    description: 'Comma-separated attack categories to test'
    required: false
  attack-count:
    description: 'Number of attacks to run'
    required: false
  format:
    description: 'Output format: table, json, summary'
    required: false
    default: 'table'
  comment:
    description: 'Post results as a PR comment (true/false)'
    required: false
    default: 'true'
  api-url:
    description: 'BotGuard API base URL (override for self-hosted)'
    required: false

outputs:
  score:
    description: 'Security score (0-100)'
    value: ${{ steps.scan.outputs.score }}
  passed:
    description: 'Whether the scan passed the threshold (true/false)'
    value: ${{ steps.scan.outputs.passed }}
  report-url:
    description: 'URL to the full security report'
    value: ${{ steps.scan.outputs.report-url }}
  session-id:
    description: 'Scan session ID'
    value: ${{ steps.scan.outputs.session-id }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install BotGuard CLI
      shell: bash
      run: npm install -g botguard-cli@latest

    - name: Run Security Scan
      id: scan
      shell: bash
      env:
        BOTGUARD_API_KEY: ${{ inputs.api-key }}
      run: |
        ARGS="--format json"

        if [ -n "${{ inputs.endpoint }}" ]; then
          ARGS="$ARGS --endpoint ${{ inputs.endpoint }}"
        fi

        if [ -n "${{ inputs.description }}" ]; then
          ARGS="$ARGS --description \"${{ inputs.description }}\""
        fi

        if [ -n "${{ inputs.system-prompt }}" ]; then
          ARGS="$ARGS --system-prompt \"${{ inputs.system-prompt }}\""
        fi

        if [ -n "${{ inputs.categories }}" ]; then
          ARGS="$ARGS --categories ${{ inputs.categories }}"
        fi

        if [ -n "${{ inputs.attack-count }}" ]; then
          ARGS="$ARGS --attack-count ${{ inputs.attack-count }}"
        fi

        if [ -n "${{ inputs.api-url }}" ]; then
          ARGS="$ARGS --api-url ${{ inputs.api-url }}"
        fi

        # Run scan and capture JSON output
        set +e
        RESULT=$(eval botguard scan $ARGS 2>&1)
        EXIT_CODE=$?
        set -e

        echo "$RESULT"

        # Parse JSON result for outputs
        SCORE=$(echo "$RESULT" | node -e "
          const lines = require('fs').readFileSync('/dev/stdin','utf8');
          try {
            const j = JSON.parse(lines);
            console.log(j.score || 0);
          } catch { console.log(0); }
        ")
        SESSION_ID=$(echo "$RESULT" | node -e "
          const lines = require('fs').readFileSync('/dev/stdin','utf8');
          try {
            const j = JSON.parse(lines);
            console.log(j.sessionId || '');
          } catch { console.log(''); }
        ")

        THRESHOLD=${{ inputs.fail-threshold }}
        if [ "$SCORE" -ge "$THRESHOLD" ] 2>/dev/null; then
          PASSED="true"
        else
          PASSED="false"
        fi

        echo "score=$SCORE" >> $GITHUB_OUTPUT
        echo "passed=$PASSED" >> $GITHUB_OUTPUT
        echo "session-id=$SESSION_ID" >> $GITHUB_OUTPUT
        echo "report-url=https://botguard.dev/report/$SESSION_ID" >> $GITHUB_OUTPUT

        # Save result for PR comment
        echo "$RESULT" > /tmp/botguard-result.json

    - name: Post PR Comment
      if: inputs.comment == 'true' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const resultPath = '/tmp/botguard-result.json';

          let score = '${{ steps.scan.outputs.score }}';
          let passed = '${{ steps.scan.outputs.passed }}';
          let sessionId = '${{ steps.scan.outputs.session-id }}';
          let reportUrl = '${{ steps.scan.outputs.report-url }}';

          let body = '';
          try {
            const raw = fs.readFileSync(resultPath, 'utf8');
            const result = JSON.parse(raw);
            const attacks = result.results?.attacks || [];
            const passedCount = attacks.filter(a => a.analysis?.passed).length;
            const failedCount = attacks.length - passedCount;
            const violations = result.results?.totalViolations || 0;

            const badge = Number(score) >= 80 ? '🟢' : Number(score) >= 50 ? '🟡' : '🔴';

            body = `## ${badge} BotGuard Security Scan\n\n`;
            body += `| Metric | Value |\n|---|---|\n`;
            body += `| **Score** | **${score}/100** |\n`;
            body += `| Passed | ${passedCount} |\n`;
            body += `| Failed | ${failedCount} |\n`;
            body += `| Violations | ${violations} |\n\n`;

            if (failedCount > 0) {
              body += `### Failed Attacks\n\n`;
              const failed = attacks.filter(a => !a.analysis?.passed).slice(0, 10);
              for (const atk of failed) {
                const sev = atk.attack?.severity || 'medium';
                const name = atk.attack?.name || atk.attack?.targetedRule || 'Unknown';
                body += `- **${sev.toUpperCase()}**: ${name}\n`;
              }
              if (failedCount > 10) {
                body += `- ... and ${failedCount - 10} more\n`;
              }
              body += '\n';
            }

            body += `[View Full Report](${reportUrl}) | [BotGuard](https://botguard.dev)\n`;
          } catch (e) {
            body = `## BotGuard Security Scan\n\nScore: **${score}/100**\n\n[View Report](${reportUrl})`;
          }

          // Find and update existing comment or create new one
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const existing = comments.find(c =>
            c.user?.login === 'github-actions[bot]' &&
            c.body?.includes('BotGuard Security Scan')
          );

          if (existing) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existing.id,
              body,
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
          }

    - name: Check Threshold
      if: inputs.fail-threshold != '0'
      shell: bash
      run: |
        SCORE=${{ steps.scan.outputs.score }}
        THRESHOLD=${{ inputs.fail-threshold }}
        if [ "$SCORE" -lt "$THRESHOLD" ] 2>/dev/null; then
          echo "::error::Security score $SCORE is below threshold $THRESHOLD"
          exit 1
        fi
        echo "Security score $SCORE meets threshold $THRESHOLD"
